server:
  port: 8072

spring:
  data:
    mongodb:
      database: BankAccount
      host: localhost
      port: 27017 

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/