server:
  port: 8078

spring:
  data:
    mongodb:
      database: Bank
      host: localhost
      port: 27017 

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8099/eureka/