server:
  port: 8076

spring:
  data:
    mongodb:
      database: Transaction
      host: localhost
      port: 27017  

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8099/eureka/
      