spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
          - Path=/customer/**
        - id: service-bank-account
          uri: lb://service-bank-account
          predicates:
          - Path=/bankAccount/**
        - id: service-credit-account
          uri: lb://service-credit-account
          predicates:
          - Path=/credit/**
        - id: service-transaction
          uri: lb://service-transaction
          predicates:
          - Path=/transaction/**
        - id: service-bank
          uri: lb://service-bank
          predicates:
          - Path=/bank/**
        - id: service-atm
          uri: lb://service-atm
          predicates:
          - Path=/atm/**     

